name: blink
description: The Staring Game.

publish_to: "none"

version: 1.2.0+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  async: ^2.8.1
  camera: ^0.9.4+3
  cloud_firestore: ^3.1.0
  device_info_plus: ^3.2.1
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  google_ml_kit: ^0.7.3
  google_sign_in: ^5.2.1
  http: ^0.13.4
  permission_handler: ^8.2.6
  provider: ^6.0.1
  flutter_webrtc:
    # path: ../flutter-webrtc
    # TODO: Fix this
    # code above is used because I had to fix null pointer exception immediately
    # so now you have to fix it on github and change dependencie path

    git:
      url: https://github.com/mishkov/flutter-webrtc.git
      ref: eyes-open-stream-rotate-adaptive
  flutter_arc_text: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
